### ISSUE TITLE
Remove shared library in casc configs

### ISSUE THREAD

**Issue by Aaquiff** [wso2/kubernetes-pipeline#20]
**Description:**
`jenkins-casc-conf.yaml` which contains the configurations for Jenkins Configuration as code has a reference to the shared library. This needs to be removed since it's no longer required.

**Fix**
Remove the following from `jenkins-casc-conf.yaml`
```yaml
unclassified:
      globalLibraries:
        libraries:
          - name: "wso2-jenkins-shared-lib"
            defaultVersion: master
            retriever:
              modernSCM:
                scm:
                  git:
                    remote: "https://github.com/Aaquiff/jenkins-shared-lib"
```
